MVCService/Controllers/AddController.cs
using MVCService.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace MVCService.Controllers
{
    public class AddController : Controller
    {
        //private DatabaseEntities db = new DatabaseEntities();

        [System.Web.Mvc.HttpPost]
        public ActionResult AddNewAnimal()
        {
            string name = Request["name"].ToString();
            string type = Request["type"].ToString();
            int age = Convert.ToInt32(Request["age"].ToString());

            Animal newAnimal = new Animal(name, type, age);

            DatabaseEntities db = new DatabaseEntities();

            try
            {
                db.Animals.Add(newAnimal);
                db.SaveChanges();
            }
            catch (Exception e)
            {
                return View("Error writing to database: " + e.ToString());
            }

            //This is how you can remove entries from the database.
            //Animal entryToBeDeleted = db.Animals.First(x => x.Name == "Mama");
            //db.Animals.Remove(entryToBeDeleted);
            //db.SaveChanges();

            //This is to refresh the page so that the table reloads from database
            return RedirectToAction("Add", "Home");
            
        }
    }
}

MVCService/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using System.Text;
using MVCService.Models;

namespace MVCService.Controllers
{
    public class AnimalController : Controller
    {


        //public List<Animal> animals = new List<Animal> 
        //{ 
        //    new Animal("Dan", "Dog", 2),
        //    new Animal("Don", "Badger", 4),
        //    new Animal("Ben", "Crow", 1)
        //};
    
        //public List<Animal> GetAllAnimals()
        //{
        //    return animals;
        //}

        //public List<Animal> CreateNewList(int minLength)
        //{
        //    List<Animal> retAnimals = new List<Animal>(animals.Count);

        //    var lenQuery = from a in animals where a.Name.Length >= minLength select a;

        //    foreach (Animal a in lenQuery)
        //        retAnimals.Add(a);

        //    return retAnimals;
        //}

        [System.Web.Mvc.HttpPost]
        public ActionResult GetAnimalNamesLongerThan()
        {

            int minLength = Convert.ToInt32(Request["minLength"].ToString());

            DatabaseEntities db = new DatabaseEntities();
            var selectedAnimals = (from a in db.Animals where a.Type.Length > minLength select a).ToList();

            Animals aList = new Animals(selectedAnimals);

            //return View(selectedAnimals);
            //return Content(aList.AnimalHtmlList);
            return RedirectToAction("Search", "Home");
        }

    }
}

MVCService/Controllers/HomeController.cs
using MVCService.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCService.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search()
        {
            ViewBag.Message = "Here you can search animals by type length.";
            //return View(new List<Animal> { new Animal("Danny", "Giraffe", 2) });
            return View(new List<Animal>());
        }

        //private WebServicesDbEntities1 db = new WebServicesDbEntities1();

        public ActionResult Add()
        {
            ViewBag.Message = "You can add a new animal to the family here.";
            using (var db = new DatabaseEntities())
            {
                return View(db.Animals.ToList());
            }

            //return View();
        }
    }
}

MVCService/Views/Home/Add.cshtml
@model IEnumerable<MVCService.Models.Animal>

@{
    ViewBag.Title = "Add";
}

<h2>View animals.</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
            </td>
        </tr>
    }

</table>

<h2>Add animals.</h2>

<fieldset>

    @*Ajax is not actyally neccessary here since the whole page is reloaded.*@
    @using (Ajax.BeginForm("AddNewAnimal", "Add",
                            new AjaxOptions { UpdateTargetId = "addAnimal" }))
    {

        <table class="table">

            <tr>
                <td>
                    @Html.Label("Name :")
                </td>
                <td>
                    @Html.TextBox("name")
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Label("Type :")
                </td>
                <td>
                    @Html.TextBox("type")
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Label("Age :")
                </td>
                <td>
                    @Html.TextBox("age")
                </td>
            </tr>
            <tr>
                <td>
                    <button>Add new animal</button>
                </td>
            </tr>


        </table>
        <div id="addAnimal"></div>
    }
</fieldset>

MVCService/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>The Zoo</h1>
    <p class="lead">Welcome to the zoo where you can see animals. You can learn more about zoos here:</p>
    <p><a href="https://en.wikipedia.org/?title=Zoo" class="btn btn-primary btn-large">Essential information &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Learn more about donkeys</h2>
        <p>Donkeys are super important and you should read about them.</p>
        <p><a class="btn btn-default" href="https://en.wikipedia.org/wiki/Donkey">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-6">
        <h2>Embark on a wonderful journey</h2>
        <p>We hope this zoo inspires you to go on safari.</p>
        <p><a class="btn btn-default" href="https://en.wikipedia.org/?title=Safari">Learn more &raquo;</a></p>
    </div>
</div>

MVCService/Views/Home/Search.cshtml
@model IEnumerable<MVCService.Models.Animal>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>


@{
    ViewBag.Title = "Search";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

@{
    //@Html.Label(Model.AnimalHtmlList);
}

<fieldset>

   @using (Ajax.BeginForm("GetAnimalNamesLongerThan", "Animal",
                            new AjaxOptions { UpdateTargetId = "searchAnimals" }))
    {
        <p>

            @Html.Label("Minimum number of characters in name :")
            @Html.TextBox("minLength")

        </p>
        <button>Search</button>
        <div id="searchAnimals"></div>
    }
</fieldset>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
            </td>
        </tr>
    }

</table>